### ISSUE TITLE
[macOS-chrome-1920-상세게시글] 댓글 내용 길 시 등록 안됨

### ISSUE THREAD

**Issue by dslov89** [100-hours-a-week/2-luis-hwang-community-fe#5]
**버그 설명**
댓글 내용이 길면 등록이 안됨

**재현하는 방법**
동작을 재현하는 단계:
1. 댓글 길게 작성
2. 댓글 작성 오류 떴다는 알림창 뜸

**예상한 동작**
댓글 등록될 줄 

**스크린샷**
<img width="1512" alt="스크린샷 2024-12-18 오후 1 36 22" src="https://github.com/user-attachments/assets/01f81b43-56cf-4325-93c9-f592d70882a2" />

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: macOS Sonoma 14.6.1
 - Browser: chrome
 - Version: 130.0.6723.59

**추가적인 내용:**
없음둥

**Comment by rivercity310** [comment]
기존 댓글 저장하는 컬럼이 VARCHAR(512)라 넘어가면 발생하는 문제였네요.
수정 완료! 감사합니다.
